spring.application.name=ParkEase-backend

# ✅ DATABASE (USE ENV VARIABLES - VERY IMPORTANT)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# PORT (Render compatible)
server.port=${PORT:8080}

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# RAZORPAY
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# GOOGLE DRIVE
google.drive.credentials-file=credentials.json
google.drive.tokens-directory=tokens
google.drive.folder-id=1PEMvjlRtYnc2jUKqbRMYOE8d-7lojTBA

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.web=DEBUG